AmbiguousRegexpLiteral:
  Enabled: false

AccessModifierIndentation:
  EnforcedStyle: outdent

AssignmentInCondition:
  Enabled: false

# Enforcing this results in a lot of unnecessary indentation.
ClassAndModuleChildren:
  Enabled: false

CollectionMethods:
  PreferredMethods:
    reduce: inject

Documentation:
  Exclude:
    - 'spec/scss_lint/*'
    - 'spec/scss_lint/linter/*'

# Ruby 1.8.7 only supports trailing dots in method chains, but Rubocop still
# reports it as an error for method calls chained onto do...end blocks. That's
# too much noise, so remove it.
DotPosition:
  Enabled: false

Eval:
  Exclude:
    - 'lib/scss_lint/sass/script.rb'

FormatString:
  Enabled: false

FileName:
  Exclude:
    - 'bin/scss-lint'
    - 'Gemfile'
    - 'Rakefile'
    - '*.gemspec'

IfUnlessModifier:
  Enabled: false

LineLength:
  Max: 100

MethodLength:
  Max: 20

# Prefer curly braces except for %i/%w/%W, since those return arrays.
PercentLiteralDelimiters:
  PreferredDelimiters:
    '%': '{}'
    '%i': '[]'
    '%q': '{}'
    '%Q': '{}'
    '%r': '{}'
    '%s': '()'
    '%w': '[]'
    '%W': '[]'
    '%x': '{}'

# Renaming `has_something?` to `something?` obfuscates whether it is a "is-a" or
# a "has-a" relationship.
PredicateName:
  Enabled: false

RegexpLiteral:
  Enabled: false

SignalException:
  Enabled: false

# Forcing a particular name (e.g. |a, e|) for inject methods prevents you from
# choosing intention-revealing names.
SingleLineBlockParams:
  Enabled: false

SpecialGlobalVars:
  Enabled: false

TrailingComma:
  Enabled: false

UselessAccessModifier:
  Enabled: false

Void:
  Enabled: false
